version: "3.7"
services:
  db:
    restart: always
    build: ./src/postgresdb
    ports:
      - "5432:5432"

  app:
    restart: always
    build: ./src/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379

  worker:
    build: ./src/worker
    user: nobody
    depends_on:
      - app
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"